
// Autogenerated, do not edit

#ifndef __ATL_SRC
#define __ATL_SRC

uint8_t nvramrc[] = ": dofield\ndoes> \ndup @ \nswap \ncell+ @ \n-rot \n+ swap\ndrop \n;\n: field \ncreate\n2dup\nswap\n,\n,\n+\ndofield\n;\n0 constant struct\n: endstruct\ncreate\n,\ndoes>\n@\n;\n: nip\nswap drop\n;\n: tuck\nswap over\n;\nUSB_TASK constant iam\nstruct\ncell field sender\n1 chars field fields\n8 chars field cmd\n16 chars field key\n32 chars field value\nendstruct /msg\nvariable init_run\nvariable out\n/msg string cmd-buffer\n/msg string rx-buffer\n: init\ninit_run @ 0= if\nhere /msg allot out !\nout @ /msg erase\n-1 init_run !\nthen\nclear\n;\n: mkmsg-set\ninit_run @ if\nout @ /msg erase\nout @ value strcpy\nout @ key strcpy\niam qid@ drop out @ sender !\n3 out @ fields !\n\"SET\" out @ cmd strcpy\nthen\n;\n: send\ninit_run @ if\nout @ swap qid@\nif\n\"Send Failed\" abort\"\nelse\nmessage!\nthen\nthen\n;\n: mkmsg-unsub\ninit_run @ if\nout @ /msg erase\nout @ key strcpy\niam qid@ out @ sender !\n2 out @ fields !\n\"UNSUB\" out @ cmd strcpy\nthen\n;\n: mkmsg-get\ninit_run @ if\nout @ /msg erase\nout @ key strcpy\niam qid@ drop out @ sender !\n2 out @ fields !\n\"GET\" out @ cmd strcpy\nthen\n;\n: mkmsg-sub\ninit_run @ if\nout @ /msg erase\nout @ key strcpy\niam qid@ drop out @\nsender\n!\n2 out @ fields !\n\"SUB\" out @ cmd\nstrcpy\nthen\n;\n: disp\ninit_run @ if\nout @ /msg dump\nthen\n;\n: .struct\ncr\n>r\n\"Sender :\" type r@ sender @ . cr\n\"Fields :\" type r@ fields c@ . cr\n\"Command:\" type r@ cmd type cr\n\"Key :\" type r@ key type cr\n\"Value :\" type r> value type cr\ncr\n;\n: msg-get\n>r\nrx-buffer /msg erase\niam qid@ r> rx-buffer message@\ndup 0x10 = if\nrx-buffer /msg dump\nthen\n;\n: cmd-eval\n>r\nr@ cmd cmd-buffer strcpy\n\" \" cmd-buffer strcat\nr@ key cmd-buffer strcat\n\" \" cmd-buffer strcat\nr> value cmd-buffer strcat\ncmd-buffer evaluate\n;\n";

#endif

