#!/usr/bin/env python

import sys
import re

def removeComments( code ):
    out=""
    hit=False

    endChar = ')'

    tmp=list( code )
    for c in tmp:
        
        if c == '(':
            hit=True
            endChar=')'

        if c == '\\':
            hit=True
            endChar='\n'

        if not hit:
            out +=c
        
        if hit and c == endChar :
            hit = False

    out.strip()
    result=re.sub(' +',' ',out)
    return result

def main():

    output=""
    if  len(sys.argv) <= 1:
        print
        print "Usage: mkSrc.py <file1.atl> .... <filen.atl>"
        print
        print "Redirect output to a file, e.g."
        print "\tmkSrc.py f1.atl f2.atl > src.h"
        print
        sys.exit(1)
    else:
        print "// "
        print "// Autogenerated, do not edit"
        print "// "
        print
        print "#ifndef __ATL_SRC"
        print "#define __ATL_SRC"

        output = 'uint8_t nvramrc[] = "'

        for file in sys.argv[1:]:
            with open(file) as inf:
                for line in inf:
                    if len(line) > 1:
                        if line[0] != '\\' and line[0] != '(':
                            output += removeComments(line)
                            output = (output.strip() + '\\n')

        output += '"'
        print
        print output
        print
        print "#endif"


# print removeComments( "test      ( test ) and \\ more" )
main()
