#!/usr/bin/env python

import getopt
import sys
import re

def usage():
    print
    print 'Usage: mkSrc.py -v -f "<file1.atl> .... <filen.atl>" -o <output.h>'
    print
    print 'Synopsys:'
    print '\tConcatenate the contents of the files given in to a string and'
    print '\tproduce a C header file.  If -o not given results are sent to stdout.'
    print 'Example:'
    print '\tmkSrc.py -f "f1.atl f2.atl" -o src.h'
    print

def removeComments( code ):
    out=""
    hit=False

    endChar = ')'

    tmp=list( code )
    for c in tmp:
        
        if c == '(':
            hit=True
            endChar=')'

        if c == '\\':
            hit=True
            endChar='\n'

        if not hit:
            out +=c
        
        if hit and c == endChar :
            hit = False

    out.strip()
    result=re.sub(' +',' ',out)
    return result

def main():

    outFile=""
    files=""
    verbose=False
    debug=False

    if  len(sys.argv) <= 1:
        usage()
        sys.exit(1)

    try:
        opts, args = getopt.getopt(sys.argv[1:], "dhf:o:v",[])
    except getopt.GetoptError as err:
        print str(err)
        usage()
        sys.exit(2)

    for o,a in opts:
        if o == "-f":
            files=a.split()
        elif o == "-d":
            debug=True
        elif o == "-h":
            usage()
            sys.exit(3)
        elif o == "-o":
            outFile = a
        elif o == "-v":
            verbose=True

    if debug:
        print "files :",files
        print "Output:" + outFile



    header =  "// \n"
    header +=  "// Autogenerated, do not edit.\n"
    header +=  "// \n"
    header += "\n"
    header +=  "#ifndef __ATL_SRC\n"
    header +=  "#define __ATL_SRC\n\n"

    header += 'uint8_t nvramrc[] = "'

    output=""
    for file in files:
        if verbose:
            print "Reading " + file
        with open(file) as inf:
            for line in inf:
                if len(line) > 1:
                    if line[0] != '\\' and line[0] != '(':
                        output += removeComments(line)
                        output = (output.strip() + '\\n')

    output += '"'

    output +="\n\n#endif\n\n"

    res=header + output

    if len(outFile) == 0:
        print
        print res
        print
    else:
        f=open(outFile,'w')
        print >>f
        print >>f, res 


# print removeComments( "test      ( test ) and \\ more" )
main()
