#!/bin/bash

# set -x

printf "\n"
printf "// Autogenerated, do not edit\n\n"
printf "#ifndef __ATL_SRC\n"
printf "#define __ATL_SRC\n\n"

printf "uint8_t nvramrc[] = \""

while read -r LINE; do 
    if [ ${#LINE} -ge 0 ]; then
        T=$(echo $LINE | grep -o '^[^\\]*')
        L=$(echo $T | grep -o '^[^(]*')

        if [  ${#L} -gt 0 ]; then
            /bin/echo -n "$L\\n"
        fi
#        if [ "$L" = " \\" ]; then
#            exit
#        else
#            /bin/echo -n "$L \\" # | sed '/^\s*$/d'
#            printf "n"
#        fi
    fi
done 
printf "\";\n\n"

printf "#endif\n\n"

