#!/bin/bash

# set -x

printf "\n"
printf "// Autogenerated, do not edit\n\n"
printf "#ifndef __ATL_SRC\n"
printf "#define __ATL_SRC\n\n"

printf "uint8_t nvramrc[] = \""

while read -r LINE; do 
    if [ ${#LINE} -ge 0 ]; then
#        printf "$LINE \\n"| tr '\n' ' ' | sed 's/  */ /g'
        printf "$LINE \\" | sed '/^\s*$/d'
        printf "n"
    fi
done 
printf "\";\n\n"

printf "#endif\n\n"

